### ISSUE TITLE
debuglog related issue

### ISSUE THREAD

**Issue by rahulguha** [nathanaschbacher/nodiak#28]
var debug = util.debuglog('http');
                 ^
TypeError: Object #<Object> has no method 'debuglog

Any idea ?

**Comment by chrispeltzer** [comment]
Can you republish to npm? While your fix has been merged into the codebase, the version installed via npm still has the issue.

**Comment by ryanwild** [comment]
@chrispeltzer It should be on npm already here are my dependencies:
```
"dependencies": {
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "~1.0.0",
    "connect-flash": "^0.1.1",
    "cookie-parser": "~1.0.1",
    "debug": "~0.7.4",
    "express": "~4.2.0",
    "express-session": "^1.8.1",
    "lodash": "^2.4.1",
    "morgan": "~1.0.0",
    "nodiak": "^0.4.3",
    "nunjucks": "^1.0.7",
    "passport": "^0.2.0",
    "passport-local": "^1.0.0",
    "static-favicon": "~1.0.0",
    "vasync": "^1.6.2"
  },
```

And I'm running node:
`v0.10.33`

All my tests pass no exceptions...
